POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Serviço 2",
    "description": "Descrição do serviço",
    "price": 155,
    "image": "https://images.unsplash.com/photo-1702234672110-dd24ddfd9e0b?q=80&w=1886&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/657b62bb3fa3e00a9918affc
###
DELETE http://localhost:3000/api/services/657b62bb3fa3e00a9918affc
###
PUT  http://localhost:3000/api/services/657b60440a5f760f6ff472d5
Content-Type: application/json

{
    "name": "Update  2",
    "description": "Descrição do serviço",
    "price": 234,
    "image": "https://images.unsplash.com/photo-1702234672110-dd24ddfd9e0b?q=80&w=1886&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}